name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths: 
      - 'server/**'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests (if any)
      run: npm test --if-present

    # Add deployment steps for your chosen platform
    # Example for Railway:
    # - name: Deploy to Railway
    #   uses: railway-app/railway-deploy@v2
    #   with:
    #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
    
    # Example for Render:
    # - name: Deploy to Render
    #   run: |
    #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
